# Generated by Django 3.0 on 2021-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_pessoa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de votos'),
        ),
    ]
