# Generated by Django 3.0 on 2021-04-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votar',
            options={'verbose_name': 'Votar', 'verbose_name_plural': 'Votar'},
        ),
    ]
