# Generated by Django 3.0 on 2021-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20210406_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votar',
            name='qtdVotos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de votos'),
        ),
    ]
